export const HTTP_GET_FETCH_REQUESTED = 'Team4/HTTP_GET_FETCH_REQUESTED';

export const HTTP_GET_FETCH_SUCCEEDED = 'Team4/HTTP_GET_FETCH_SUCCEEDED';

export const HTTP_GET_FETCH_RESPONSE_ERROR = 'Team4/HTTP_GET_FETCH_RESPONSE_ERROR';

export const HTTP_GET_FETCH_FAILED = 'Team4/HTTP_GET_FETCH_FAILED';

export const SHOW_ALL_DATA = 'Team4/SHOW_ALL_DATA';

export const SHOW_EVEN_DATA = 'Team4/SHOW_EVEN_DATA';

export const SHOW_ODD_DATA = 'Team4/SHOW_ODD_DATA';

export const CHANGE_SWITCH_STATUS = 'Team4/CHANGE_SWITCH_STATUS';
