//计数器方法
export const INCREMENT = 'Team1/INCREMENT';
export const DECREMENT = 'Team1/DECREMENT';
export const INITMENT = 'Team1/INITMENT';

//获取数据
export const REQUESTDATA = 'Team1/REQUESTDATA';
export const REQUESTDATASUCCESS = 'Team1/REQUESTDATASUCCESS';
export const REQUESTDATAERROR = 'Team1/REQUESTDATAERROR';
export const REQUESTDATAFAILD = 'Team1/REQUESTDATAFAILD';



