export const HTTP_GET_FETCH_REQUESTED = 'Team3/HTTP_GET_FETCH_REQUESTED';

export const HTTP_GET_FETCH_SUCCEEDED = 'Team3/HTTP_GET_FETCH_SUCCEEDED';

export const HTTP_GET_FETCH_RESPONSE_ERROR = 'Team3/HTTP_GET_FETCH_RESPONSE_ERROR';

export const HTTP_GET_FETCH_FAILED = 'Team3/HTTP_GET_FETCH_FAILED';
